### PR TITLE
Add Signal method

### PR DESCRIPTION
**Pull request by socieboy**
I haven't write any tests, but i think this is a starting point to a missing function of the sdk.

### CODE REVIEW

**Comment by socieboy** [comment]
Anyone following this thread?

**Comment by stephenlb** [comment]
@socieboy thank you  🙌

**Review by 650elx — COMMENTED** [review]
@socieboy Thanks for your contribution!

We will write some tests and improvements and release this code within one of the incoming public releases.

**Comment by socieboy** [comment]
Thanks.

**Comment by seba-aln** [comment]
This change is included in the v4.5.0 release.
Thank you for your contribution

**Pull request closed without merging**
