### PR TITLE
RevokeToken functionality, fix Signal request

### PR DESCRIPTION
**Pull request by seba-aln**
feat: revokeToken method

fix: fixed error in Signal request

### CODE REVIEW

**Review by 650elx — DISMISSED** [review]
LGTM

**Comment by seba-aln** [comment]
@client-engineering-bot release

**Review by 650elx — DISMISSED** [review]
LGTM

**Comment by parfeon** [comment]
um. Not sure about that :(
`v` prefix has been added to `composer`

**Comment by seba-aln** [comment]
@client-engineering-bot release

**Review by techwritermat — APPROVED** [review]

**Review by techwritermat — APPROVED** [review]

**Review by raipubnub — APPROVED** [review]
LGTM!

**Pull request merged**
