### PR TITLE
Implementation of the Fire method for the PHP SDK

### PR DESCRIPTION
**Pull request by socieboy**
No sure if I'm doing it right! but I would like your feedback how to implement the fire method on the SDK.

### CODE REVIEW

**Comment by qsoftdevelopment** [comment]
@socieboy I have to review the code first. Then I will get back to you.

**Comment by qsoftdevelopment** [comment]
@socieboy Hi, we have turned this to a Feature Request. The feature is in the progress and we should have something very soon.

**Comment by qsoftdevelopment** [comment]
@socieboy The feature has been implemented. We are merging PR to master 
https://github.com/pubnub/php/pull/27

**Comment by socieboy** [comment]
thanks

**Pull request closed without merging**
